version: '3.1'

services:

    zookeeper:
      image: 'bitnami/zookeeper:latest'
      ports:
        - '2181:2181'
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes


    kafka:
      image: 'bitnami/kafka:latest'
      user: root
      ports:
        - '9092:9092'
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - ./Kafka:/bitnami/kafka
      depends_on:
        - zookeeper

    jaeger:
      container_name: jaeger
      image: 'jaegertracing/all-in-one:latest'
      ports:
        - "16686:16686"  # Jaeger UI
        - "14250:14250"  # Jaeger Agent

    postgresql:
      image: 'bitnami/postgresql:latest'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - POSTGRESQL_USERNAME=bn_keycloak
        - POSTGRESQL_DATABASE=bitnami_keycloak
      volumes:
        - 'postgresql_data:/bitnami/postgresql'

    keycloak:
      image: 'bitnami/keycloak:latest'
      ports:
        - "6789:8080"
      environment:
        - KEYCLOAK_CREATE_ADMIN_USER=true
      depends_on:
        - postgresql
      volumes:
        - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'

volumes:
  postgresql_data : {}